import 'dart:async';

import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// The card sounds, all generated by `tool/generate_sounds.dart`.
enum Sfx {
  /// A card is turned over and leaves the spread.
  flip('sounds/flip.wav', players: 3),

  /// Cards fly onto the table.
  deal('sounds/deal.wav'),

  /// The deck is gathered up before a reshuffle.
  shuffle('sounds/shuffle.wav'),

  /// The last card standing is revealed.
  reveal('sounds/reveal.wav');

  const Sfx(this.asset, {this.players = 1});

  /// Path under `assets/`, as [AssetSource] expects it.
  final String asset;

  /// How many voices this sound needs; only flips overlap in practice.
  final int players;
}

/// Card sounds are wired up end to end but switched off: the synthesised
/// waveforms are not good enough to ship.
///
/// Flip this to `true` to bring the feature back — it restores both playback
/// and the "Звуки карт" row in settings, and needs nothing else. The stored
/// preference is left untouched meanwhile, so whatever the user last chose
/// comes back with it.
const bool kCardSoundsEnabled = false;

/// Overall level. The waveforms are already cut at about −4 dBFS, so this
/// only takes the edge off.
const double kSfxGain = 0.75;

/// Plays the short card sounds.
///
/// Every call is fire-and-forget and swallows its errors: a machine with no
/// audio device, or a test with no plugin, must not take the app down. After
/// the first failure the board goes quiet for good rather than retrying on
/// every card.
///
/// Note that `AudioPlayer`'s constructor starts creating the native player in
/// the background, and every call here must be awaited: a dropped future from
/// one of its methods surfaces a missing plugin as an unhandled zone error
/// instead of something we can catch.
class SoundBoard {
  SoundBoard();

  final Map<Sfx, List<AudioPlayer>> _voices = <Sfx, List<AudioPlayer>>{};
  final Map<Sfx, int> _next = <Sfx, int>{};
  bool _unavailable = false;
  bool _disposed = false;

  /// Set when playback failed, so the cause is visible while debugging.
  Object? lastError;

  /// False once playback has failed and the board has given up.
  bool get available => !_unavailable;

  Future<void> play(Sfx sfx) async {
    if (_unavailable || _disposed) return;
    try {
      final ring = await _voicesFor(sfx);
      if (ring.isEmpty || _disposed) return;

      final index = (_next[sfx] ?? 0) % ring.length;
      _next[sfx] = index + 1;
      final player = ring[index];

      await player.stop();
      if (_disposed) return;
      await player.play(AssetSource(sfx.asset), volume: kSfxGain);
    } catch (error, stack) {
      _unavailable = true;
      lastError = error;
      debugPrint('Card sounds unavailable: $error\n$stack');
    }
  }

  Future<List<AudioPlayer>> _voicesFor(Sfx sfx) async {
    final existing = _voices[sfx];
    if (existing != null) return existing;

    final ring = <AudioPlayer>[];
    try {
      for (var i = 0; i < sfx.players; i++) {
        final player = AudioPlayer();
        // setReleaseMode waits on the player's creation internally, so
        // awaiting it both configures the voice and surfaces a missing
        // plugin here, where it can be caught.
        await player.setReleaseMode(ReleaseMode.stop);
        ring.add(player);
      }
    } catch (_) {
      for (final player in ring) {
        _disposeQuietly(player);
      }
      rethrow;
    }
    _voices[sfx] = ring;
    return ring;
  }

  void dispose() {
    _disposed = true;
    for (final ring in _voices.values) {
      for (final player in ring) {
        _disposeQuietly(player);
      }
    }
    _voices.clear();
  }

  static void _disposeQuietly(AudioPlayer player) {
    unawaited(player.dispose().catchError((Object _) {}));
  }
}
